name: GamerStation Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: |
          composer install
          cp .env.production .env
          php artisan key:generate --ansi

      - name: Deploy Laravel Project
        if: github.ref == 'refs/heads/main'
        run: |
          # Deploy application files
          sshpass -p 'FCU3ijxAAcrN32' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ gstp2951@103.247.10.176:/home/gstp2951/repo/dir/

          # Update server
          sshpass -p 'FCU3ijxAAcrN32' ssh -o StrictHostKeyChecking=no gstp2951@103.247.10.176 'cd /home/gstp2951/repo/dir && php artisan config:cache && php artisan route:cache && php artisan view:cache'

      - name: Create Symlink
        run: |
          sshpass -p 'FCU3ijxAAcrN32' ssh -o StrictHostKeyChecking=no gstp2951@103.247.10.176 'bash -s' < scripts/create_symlink.sh

      - name: Set Permissions
        run: |
          sshpass -p 'FCU3ijxAAcrN32' ssh -o StrictHostKeyChecking=no gstp2951@103.247.10.176 'find /home/gstp2951/repo/dir/storage/ -type d -exec chmod 775 {} \;'
          sshpass -p 'FCU3ijxAAcrN32' ssh -o StrictHostKeyChecking=no gstp2951@103.247.10.176 'find /home/gstp2951/repo/dir/bootstrap/cache/ -type d -exec chmod 775 {} \;'

          # Set permissions for the public directory if needed
          sshpass -p 'FCU3ijxAAcrN32' ssh -o StrictHostKeyChecking=no gstp2951@103.247.10.176 'find /home/gstp2951/public_html/ -type d -exec chmod 755 {} \;'
          sshpass -p 'FCU3ijxAAcrN32' ssh -o StrictHostKeyChecking=no gstp2951@103.247.10.176 'find /home/gstp2951/public_html/ -type f -exec chmod 644 {} \;'
